CASE {type} WHEN 'Assembly Build' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/build.nl?id=',{internalid}) WHEN 'Assembly Unbuild' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/unbuild.nl?id=',{internalid}) WHEN 'Bill' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/vendbill.nl?id=',{internalid}) WHEN 'Bill CCard' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/vendcard.nl?id=',{internalid})
WHEN 'Bill Credit' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/vendcred.nl?id=',{internalid})
WHEN 'Bin Putaway Worksheet' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/binwksht.nl?id=',{internalid})
WHEN 'Bin Transfer' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/bintrnfr.nl?id=',{internalid})
WHEN 'Bill Payment' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/vendpymt.nl?id=',{internalid})
WHEN 'Cash Refund' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/cashrfnd.nl?id=',{internalid})
WHEN 'Cash Sale' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/cashsale.nl?id=',{internalid})
WHEN 'CCard Refund' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/cardrfnd.nl?id=',{internalid})
WHEN 'Check' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/check.nl?id=',{internalid})
WHEN 'Commission' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/commissn.nl?id=',{internalid})
WHEN 'Credit Card' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/cardchrg.nl?id=',{internalid})
WHEN 'Credit Memo' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custcred.nl?id=',{internalid})
WHEN 'Currency Revaluation' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/fxreval.nl?id=',{internalid})
WHEN 'Customer Deposit' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custdep.nl?id=',{internalid})
WHEN 'Customer Refund' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custrfnd.nl?id=',{internalid})
WHEN 'Deposit' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/deposit.nl?id=',{internalid})
WHEN 'Deposit Application' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/depappl.nl?id=',{internalid})
WHEN 'Expense Report' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/exprept.nl?id=',{internalid})
WHEN 'Inventory Adjustment' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/invadjst.nl?id=',{internalid})
WHEN 'Inventory Count' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/invcount.nl?id=',{internalid})
WHEN 'Inventory Distribution' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/invdistr.nl?id=',{internalid})
WHEN 'Inventory Transfer' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/invtrnfr.nl?id=',{internalid})
WHEN 'Inventory Worksheet' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/invwksht.nl?id=',{internalid})
WHEN 'InvoiceCustInvc' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custinvc.nl?id=',{internalid})
WHEN 'Item Fulfillment' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/itemship.nl?id=',{internalid})
WHEN 'Item Receipt' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/itemrcpt.nl?id=',{internalid})
WHEN 'Journal' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/journal.nl?id=',{internalid})
WHEN 'Opportunity' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/opprtnty.nl?id=',{internalid})
WHEN 'Payment' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custpymt.nl?id=',{internalid})
WHEN 'Purchase Order' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/purchord.nl?id=',{internalid})
WHEN 'Quote' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/estimate.nl?id=',{internalid})
WHEN 'Return Authorization' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/rtnauth.nl?id=',{internalid})
WHEN 'Sales Order' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/salesord.nl?id=',{internalid})
WHEN 'Sales Tax Payment' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/taxpymt.nl?id=',{internalid})
WHEN 'Statement Charge' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/custchrg.nl?id=',{internalid})
WHEN 'Transfer' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/transfer.nl?id=',{internalid})
WHEN 'Transfer Order' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/trnfrord.nl?id=',{internalid})
WHEN 'Vendor Return Authorization' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/vendauth.nl?id=',{internalid})
WHEN 'Work Order' THEN CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/workord.nl?id=',{internalid})
ELSE 'Could not create link. Please contact administrator.' END


CONCAT('https://8578641.app.netsuite.com/app/accounting/transactions/' , CONCAT( {typecode} , CONCAT( '.nl?id' , CONCAT( {internalid} ))))

'https://8578641.app.netsuite.com/app/accounting/transactions/' || {typecode} || '.nl?id' || {internalid} 